setup:
  seed: 2
  use_gpu: False

train:
  name: 'simple_spread'
  n_episodes: 10000
  verbose: 50

agent:
  update_start: 10  # n° episodes before the network updates start
  polyak: True
  tg_update: 5

  gamma: 0.10 #Gamma alto =  ricompensa a lungo termine // Gamma basso = breve termine
  tau: 0.005

  eps: 1
  eps_min: 0.05
  eps_d: 0.995

  buffer:
    size: 50000 
    batch: 128

  dnn:
    h_layers: 2
    h_size: 64
    print_model: False


  
      

